server:
  port: 8888

spring:
  datasource:
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://172.19.240.234:3306/blog?characterEncoding=utf-8&useSSL=false
  redis:
    host: 172.19.240.234
    port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



